import {LEVELS} from './words-data.js';import {Audio} from '../js/arcade-audio.js';
const $=s=>document.querySelector(s),A=$('#arena'),L=$('#layer'),S=$('#status'),M=$('#modal'),K=$('#keys');let unlocked=+(localStorage.getItem('tn_vd_unlock')||1),level=+localStorage.getItem('tn_vd_level')||1,st={e:[],lock:null,typed:0,ok:0,miss:0,done:0,score:0,combo:0,lives:3,start:0,last:performance.now(),spawn:0,run:false};
const mobile=()=>K.innerHTML=['qwertyuiop','asdfghjkl','zxcvbnm'].map(r=>[...r].map(k=>`<button data-k="${k}">${k}</button>`).join('')).join('');mobile();K.onclick=e=>e.target.dataset.k&&key(e.target.dataset.k);
function cfg(){return LEVELS[level-1]}function mult(){return st.combo>=12?2:st.combo>=6?1.5:st.combo>=3?1.2:1}function acc(){return st.typed?Math.round(st.ok/st.typed*100):100}function hud(){let mins=Math.max((performance.now()-st.start)/60000,.01);$('#lvl').textContent=level;$('#wpm').textContent=Math.round(st.ok/5/mins);$('#acc').textContent=acc()+'%';$('#combo').textContent='x'+mult();$('#score').textContent=Math.floor(st.score);$('#hearts').textContent='♥'.repeat(st.lives)+'♡'.repeat(3-st.lives);$('#count').textContent=`${st.done} / ${cfg().target}`}
function spawn(boss=false){if(st.e.length>=cfg().active||st.done>=cfg().target)return;let w=cfg().words[Math.floor(Math.random()*cfg().words.length)],el=document.createElement('div');el.className='word';el.innerHTML=`<span class="left">${w.word}</span><div style="font-family:Mukta;color:#fbbf24;font-size:13px">${w.meaning}</div>`;let e={id:Math.random(),word:w.word,meaning:w.meaning,p:0,x:50+Math.random()*40-20,y:-30,v:cfg().speed*(boss?1.55:1),el,boss};el.style.left=e.x+'%';L.appendChild(el);st.e.push(e)}
function render(e){e.el.style.top=e.y+'px';e.el.innerHTML=`<span class="hit">${e.word.slice(0,e.p)}</span><span class="left">${e.word.slice(e.p)}</span><div style="font-family:Mukta;color:#fbbf24;font-size:13px">${e.meaning}</div>`;e.el.classList.toggle('locked',st.lock===e.id)}
function complete(e){st.done++;st.combo++;st.score+=Math.round(e.word.length*100*mult());e.el.remove();st.e=st.e.filter(x=>x!==e);if(st.lock===e.id)st.lock=null;Audio.explode();if(st.combo===3||st.combo===6||st.combo===12)Audio.combo(st.combo);if(st.done>=cfg().target&&st.e.length===0)finish(true)}
function lose(e){st.lives--;st.combo=0;e.el.remove();st.e=st.e.filter(x=>x!==e);if(st.lock===e.id)st.lock=null;Audio.danger();A.classList.add('shake');setTimeout(()=>A.classList.remove('shake'),350);if(st.lives<=0)finish(false)}
function key(c){if(!st.run||!/^[a-z]$/i.test(c))return;Audio.init();st.typed++;let e=st.lock?st.e.find(x=>x.id===st.lock):st.e.filter(x=>x.word[0]===c.toLowerCase()).sort((a,b)=>b.y-a.y)[0];if(!e){st.miss++;st.combo=0;Audio.click();S.textContent='Miss — combo reset';hud();return}if(st.lock===null){st.lock=e.id;Audio.power()}if(e.word[e.p]!==c.toLowerCase()){st.miss++;st.combo=0;Audio.click();S.textContent=`Wrong key — expected ${e.word[e.p]}`;hud();return}e.p++;st.ok++;Audio.match();render(e);S.textContent=`Locked: ${e.word}`;if(e.p===e.word.length)complete(e);hud()}
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Backspace'){e.preventDefault();return}key(e.key)});
function finish(win){if(!st.run)return;st.run=false;win?Audio.level():Audio.over();let best=+(localStorage.getItem('tn_arcade_vocab_best')||0);localStorage.setItem('tn_arcade_vocab_best',Math.max(best,Math.floor(st.score)));if(win&&level===unlocked&&unlocked<25){unlocked++;localStorage.setItem('tn_vd_unlock',unlocked)}M.innerHTML=`<div class="modal"><div><div style="font-size:35px;color:${win?'var(--cyan)':'var(--pink)'}">${win?'🏆':'💥'}</div><h2>${win?'Level Cleared':'Defense Failed'}</h2><p>Level ${level} • Score ${Math.floor(st.score)} • Accuracy ${acc()}%</p><div class="actions"><button class="btn" id="again">Retry</button>${win&&level<25?'<button class="btn primary" id="next">Next Level</button>':''}<a class="btn" href="../index.html">Arcade</a></div></div></div>`;$('#again').onclick=()=>start(level);if($('#next'))$('#next').onclick=()=>start(++level)}
function start(n){level=n;localStorage.setItem('tn_vd_level',level);st={e:[],lock:null,typed:0,ok:0,miss:0,done:0,score:0,combo:0,lives:3,start:performance.now(),last:performance.now(),spawn:0,run:true};L.innerHTML='';M.innerHTML='';A.focus();Audio.start();spawn();requestAnimationFrame(loop)}function loop(t){if(!st.run)return;let dt=Math.min(35,t-st.last);st.last=t;st.spawn+=dt;if(st.spawn>cfg().interval*1000){st.spawn=0;spawn()}let danger=A.clientHeight*.82;for(let e of [...st.e]){e.y+=e.v*dt;render(e);if(e.y>danger)lose(e)}hud();requestAnimationFrame(loop)}start(Math.min(25,Math.max(1,level)));
